# http://docs.travis-ci.com/user/languages/r/
language: r
cache: packages
# dist: trusty

r:
  - release
  - 3.3
  - oldrel
  - devel

r_packages:
  - covr
  - lintr



# This option forces all WARNINGS from R CMD check to become build failures (default true).
# This is especially helpful when preparing your package for submission to CRAN.
warnings_are_errors: true

# whitelist of branches that shall be built
branches:
  only:
  - master

# Taken from: https://github.com/lockedata/HIBPwned/blob/master/.travis.yml
after_script:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'

# https://github.com/codecov/example-r
after_success:
  - Rscript -e 'library(covr); codecov()'
