---
title: "Error handling in R with tryCatchLog:
        Catching, logging, post-mortem analysis"
author: "Jürgen Altfeld"
date: "`r Sys.Date()`"
output:
    rmarkdown::html_vignette
#    rmarkdown::html_document
#        toc: yes
#        toc_depth: 1
#        number_sections: true
#
# Child Rmd files are currently not supported as vignettes in R so I had to rename
# the file endings from "Rmd" to "Rmd_child" as workaround until the R issue is solved and released.
# See:
# https://github.com/yihui/knitr/issues/1540
# https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17416
vignette: >
  %\VignetteIndexEntry{Error handling in R with tryCatchLog: Catching, logging, post-mortem analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

For a slide version of this vignette (e. g. for trainings and presentations) see:

https://aryoda.github.io/tutorials/tryCatchLog/tryCatchLog-intro-slides.html




```{r child = "01_license.Rmd_child"}
```



```{r child = "05_overview.Rmd_child"}
```



```{r child = "02_toc.Rmd_child"}
```



```{r child = "10_standard_R_conditions.Rmd_child"}
```



```{r child = "20_tryCatchLog.Rmd_child"}
```



```{r child = "90_appendix.Rmd_child"}
```


